import {
    Combine,
    Split,
    Minimize,
    FileText,
    FileBarChart,
    FileSpreadsheet,
    Image as ImageIcon,
    FileImage,
    PenTool,
    Hash,
    Stamp,
    RotateCw,
    Globe,
    Unlock,
    Lock,
    LayoutGrid,
    Archive,
    Wrench
} from 'lucide-react';

export const TOOLS = [
    {
        id: 'merge-pdf',
        name: 'Merge PDF',
        description: 'Combine PDFs in the order you want with the easiest PDF merger available.',
        icon: Combine,
        href: '/tools/merge',
        color: '#E53E3E', // Red-ish, similar to iLovePDF
    },
    {
        id: 'split-pdf',
        name: 'Split PDF',
        description: 'Separate one page or a whole set for easy conversion into independent PDF files.',
        icon: Split,
        href: '/tools/split',
        color: '#DD6B20', // Orange
    },
    {
        id: 'compress-pdf',
        name: 'Compress PDF',
        description: 'Reduce file size while optimizing for maximal PDF quality.',
        icon: Minimize,
        href: '/tools/compress',
        color: '#38A169', // Green
    },
    {
        id: 'pdf-to-word',
        name: 'PDF to Word',
        description: 'Easily convert your PDF files into easy to edit DOC and DOCX documents.',
        icon: FileText,
        href: '/tools/pdf-to-word',
        color: '#3182CE', // Blue
    },
    {
        id: 'pdf-to-powerpoint',
        name: 'PDF to Powerpoint',
        description: 'Turn your PDF files into easy to edit PPT and PPTX slideshows.',
        icon: FileBarChart,
        href: '/tools/pdf-to-powerpoint',
        color: '#D69E2E', // Yellow
    },
    {
        id: 'pdf-to-excel',
        name: 'PDF to Excel',
        description: 'Pull data straight from PDFs into Excel spreadsheets in a few short seconds.',
        icon: FileSpreadsheet,
        href: '/tools/pdf-to-excel',
        color: '#38A169',
    },
    {
        id: 'word-to-pdf',
        name: 'Word to PDF',
        description: 'Make DOC and DOCX files easy to read by converting them to PDF.',
        icon: FileText,
        href: '/tools/word-to-pdf',
        color: '#E53E3E',
    },
    {
        id: 'powerpoint-to-pdf',
        name: 'Powerpoint to PDF',
        description: 'Make PPT and PPTX slideshows easy to view by converting them to PDF.',
        icon: FileBarChart,
        href: '/tools/powerpoint-to-pdf',
        color: '#E53E3E',
    },
    {
        id: 'excel-to-pdf',
        name: 'Excel to PDF',
        description: 'Make EXCEL spreadsheets easy to read by converting them to PDF.',
        icon: FileSpreadsheet,
        href: '/tools/excel-to-pdf',
        color: '#E53E3E',
    },
    {
        id: 'sign-edit-pdf',
        name: 'Sign/Edit PDF',
        description: 'Add text, images, shapes or freehand annotations to a PDF document. Fill and sign your PDFs.',
        icon: PenTool,
        href: '/app',
        color: '#805AD5', // Purple
    },
    {
        id: 'pdf-to-jpg',
        name: 'PDF to JPG',
        description: 'Convert each PDF page into a JPG or extract all images contained in a PDF.',
        icon: ImageIcon,
        href: '/tools/pdf-to-jpg',
        color: '#D69E2E',
    },
    {
        id: 'jpg-to-pdf',
        name: 'JPG to PDF',
        description: 'Adjust orientation and margins. Convert JPG images to PDF in seconds.',
        icon: FileImage,
        href: '/tools/jpg-to-pdf',
        color: '#D69E2E',
    },
    {
        id: 'page-numbers',
        name: 'Page Numbers',
        description: 'Add page numbers into PDFs with ease. Choose your positions, dimensions, typography.',
        icon: Hash,
        href: '/tools/page-numbers',
        color: '#E53E3E',
    },
    {
        id: 'watermark',
        name: 'Add Watermark',
        description: 'Stamp an image or text over your PDF in seconds. Choose the typography, transparency and position.',
        icon: Stamp,
        href: '/tools/watermark',
        color: '#3182CE',
    },
    {
        id: 'rotate-pdf',
        name: 'Rotate PDF',
        description: 'Rotate your PDFs the way you need them. You can even rotate multiple PDFs at once!',
        icon: RotateCw,
        href: '/tools/rotate',
        color: '#3182CE',
    },
    {
        id: 'html-to-pdf',
        name: 'HTML to PDF',
        description: 'Convert webpages in HTML to PDF. Capture and save full webpages as PDF records.',
        icon: Globe,
        href: '/tools/html-to-pdf',
        color: '#3182CE',
    },
    {
        id: 'unlock-pdf',
        name: 'Unlock PDF',
        description: 'Remove PDF password security, giving you the freedom to use your PDFs as you want.',
        icon: Unlock,
        href: '/tools/unlock',
        color: '#718096',
    },
    {
        id: 'protect-pdf',
        name: 'Protect PDF',
        description: 'Encrypt your PDF with a password to keep sensitive data confidential.',
        icon: Lock,
        href: '/tools/protect',
        color: '#718096',
    },
    {
        id: 'organize-pdf',
        name: 'Organize PDF',
        description: 'Sort pages of your PDF file however you like. Delete PDF pages or add PDF pages to your document at your convenience.',
        icon: LayoutGrid,
        href: '/tools/organize',
        color: '#E53E3E',
    },
    {
        id: 'pdf-to-pdfa',
        name: 'PDF to PDF/A',
        description: 'Convert PDF to PDF/A, the ISO-standardized version of PDF specialized for the digital preservation of electronic documents.',
        icon: Archive,
        href: '/tools/pdf-to-pdfa',
        color: '#38A169',
    },
    {
        id: 'repair-pdf',
        name: 'Repair PDF',
        description: 'Repair a damaged PDF and recover data from corrupt PDF. Fix PDF files with our Repair tool.',
        icon: Wrench,
        href: '/tools/repair',
        color: '#718096',
    }
];
